hello/config/routes.rb
Rails.application.routes.draw do
  get 'sigma/ror'

  resources :articleees
  get 'ravan/ram'
  get 'ravan/arm'
  
  get 'welcome/index'
  resources :articles
  root 'welcome#index'
end

hello/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

hello/app/models/article.rb
class Article < ApplicationRecord
end

hello/app/models/articlee.rb
class Articlee < ApplicationRecord
end

hello/app/models/articleee.rb
class Articleee < ApplicationRecord
end

hello/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

hello/app/controllers/articleees_controller.rb
class ArticleeesController < ApplicationController
  before_action :set_articleee, only: [:show, :edit, :update, :destroy]

  # GET /articleees
  # GET /articleees.json
  def index
    @articleees = Articleee.all
  end

  # GET /articleees/1
  # GET /articleees/1.json
  def show
  end

  # GET /articleees/new
  def new
    @articleee = Articleee.new
  end

  # GET /articleees/1/edit
  def edit
  end

  # POST /articleees
  # POST /articleees.json
  def create
    @articleee = Articleee.new(articleee_params)

    respond_to do |format|
      if @articleee.save
        format.html { redirect_to @articleee, notice: 'Articleee was successfully created.' }
        format.json { render :show, status: :created, location: @articleee }
      else
        format.html { render :new }
        format.json { render json: @articleee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articleees/1
  # PATCH/PUT /articleees/1.json
  def update
    respond_to do |format|
      if @articleee.update(articleee_params)
        format.html { redirect_to @articleee, notice: 'Articleee was successfully updated.' }
        format.json { render :show, status: :ok, location: @articleee }
      else
        format.html { render :edit }
        format.json { render json: @articleee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articleees/1
  # DELETE /articleees/1.json
  def destroy
    @articleee.destroy
    respond_to do |format|
      format.html { redirect_to articleees_url, notice: 'Articleee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_articleee
      @articleee = Articleee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def articleee_params
      params.require(:articleee).permit(:title, :descrption)
    end
end

hello/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    def show
        @article = Article.find(params[:id])
      end
    def new
    end
    
def create

    @article = Article.new(article_params)
   
    @article.save
    redirect_to @article
  end
   
  private
    def article_params
      params.require(:article).permit(:title, :text)
    end
  end

hello/app/controllers/ravan_controller.rb
class RavanController < ApplicationController
  def ram
    puts "sdvffdsdc"
  end
  def arm
    puts "sdfcs"
  end
end

hello/app/controllers/sigma_controller.rb
class SigmaController < ApplicationController
  def ror
  
    
  end
end

hello/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

hello/app/helpers/application_helper.rb
module ApplicationHelper
end

hello/app/helpers/articleees_helper.rb
module ArticleeesHelper
end

hello/app/helpers/articles_helper.rb
module ArticlesHelper
end

hello/app/helpers/ravan_helper.rb
module RavanHelper
end

hello/app/helpers/sigma_helper.rb
module SigmaHelper

    
end

hello/app/helpers/welcome_helper.rb
module WelcomeHelper
end

hello/app/views/articleees/_form.html.erb
<%= form_with(model: articleee, local: true) do |form| %>
  <% if articleee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(articleee.errors.count, "error") %> prohibited this articleee from being saved:</h2>

      <ul>
      <% articleee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :articleee_title %>
  </div>

  <div class="field">
    <%= form.label :descrption %>
    <%= form.text_area :descrption, id: :articleee_descrption %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

hello/app/views/articleees/edit.html.erb
<h1>Editing Articleee</h1>

<%= render 'form', articleee: @articleee %>

<%= link_to 'Show', @articleee %> |
<%= link_to 'Back', articleees_path %>

hello/app/views/articleees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Articleees</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Descrption</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articleees.each do |articleee| %>
      <tr>
        <td><%= articleee.title %></td>
        <td><%= articleee.descrption %></td>
        <td><%= link_to 'Show', articleee %></td>
        <td><%= link_to 'Edit', edit_articleee_path(articleee) %></td>
        <td><%= link_to 'Destroy', articleee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Articleee', new_articleee_path %>

hello/app/views/articleees/new.html.erb
<h1>New Articleee</h1>

<%= render 'form', articleee: @articleee %>

<%= link_to 'Back', articleees_path %>

hello/app/views/articleees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @articleee.title %>
</p>

<p>
  <strong>Descrption:</strong>
  <%= @articleee.descrption %>
</p>

<%= link_to 'Edit', edit_articleee_path(@articleee) %> |
<%= link_to 'Back', articleees_path %>

hello/app/views/articles/new.html.erb
<%= form_with scope: :article,url: articles_path, local: true do |form| %>
    <p>
      <%= form.label :title %><br>
      <%= form.text_field :title %>
    </p>
   
    <p>
      <%= form.label :text %><br>
      <%= form.text_area :text %>
    </p>
    
   
    <p>
      <%= form.submit %>
    </p>
  <% end %>

  

hello/app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

hello/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hello</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

hello/app/views/ravan/arm.html.erb
<h1>ram</h1>
<%= link_to 'ram', ravan_ram_path%>

hello/app/views/ravan/ram.html.erb
<h1>arm</h1>
<%= link_to 'am', ravan_arm_path%>

hello/app/views/sigma/ror.html.erb
<h1>Sigma#ror</h1>
<p>Find me in app/views/sigma/ror.html.erb</p>

<table>
<tr>
<td>marks</td>
<td>97</td>
</tr>
<tr>
<td>marks</td>
<td>98</td>
</tr><tr>
<td>marks</td>
<td>99</td>
</tr>
</table>

hello/app/views/welcome/index.html.erb
<h1>Hello, Rails!&&&&efrth</h1>